### ISSUE TITLE
doorman breaks with "tr" locale

### ISSUE THREAD

**Issue by gwillem** [FriendsOfFlarum/doorman#18]
When locale is set to "tr" and doorman is activated, Flarum crashes and logs:

```
Next Symfony\Component\Translation\Exception\InvalidResourceException: Error parsing YAML, invalid file "/app/vendor/reflar/doorman/resources/locale/tr.yml" in /app/vendor/symfony/translation/Loader/YamlFileLoader.php:50
Stack trace:
#0 /app/vendor/symfony/translation/Loader/FileLoader.php(36): Symfony\Component\Translation\Loader\YamlFileLoader->loadResource('/app/vendor/ref...')
#1 /app/vendor/flarum/core/src/Locale/PrefixedYamlFileLoader.php(23): Symfony\Component\Translation\Loader\FileLoader->load('/app/vendor/ref...', 'tr', 'messages')
#2 /app/vendor/symfony/translation/Translator.php(381): Flarum\Locale\PrefixedYamlFileLoader->load(Array, 'tr', 'messages')
#3 /app/vendor/symfony/translation/Translator.php(277): Symfony\Component\Translation\Translator->doLoadCatalogue('tr')
#4 /app/vendor/symfony/translation/Translator.php(314): Symfony\Component\Translation\Translator->initializeCatalogue('tr')
#5 /app/vendor/symfony/translation/Translator.php(299): Symfony\Component\Translation\Translator->dumpCatalogue('tr', Object(Symfony\Component\Config\ConfigCache))
#6 /app/vendor/symfony/config/ConfigCacheFactory.php(46): Symfony\Component\Translation\Translator->Symfony\Component\Translation\{closure}(Object(Symfony\Component\Config\ConfigCache))
#7 /app/vendor/symfony/translation/Translator.php(300): Symfony\Component\Config\ConfigCacheFactory->cache('/app/public/../...', Object(Closure))
#8 /app/vendor/symfony/translation/Translator.php(265): Symfony\Component\Translation\Translator->initializeCacheCatalogue('tr')
#9 /app/vendor/symfony/translation/Translator.php(241): Symfony\Component\Translation\Translator->loadCatalogue('tr')
#10 /app/vendor/flarum/core/src/Locale/Translator.php(35): Symfony\Component\Translation\Translator->getCatalogue('tr')
#11 /app/vendor/symfony/translation/Translator.php(198): Flarum\Locale\Translator->getCatalogue('tr')
#12 /app/vendor/flarum/core/src/Api/Serializer/GroupSerializer.php(66): Symfony\Component\Translation\Translator->trans('core.group.admi...')
#13 /app/vendor/flarum/core/src/Api/Serializer/GroupSerializer.php(53): Flarum\Api\Serializer\GroupSerializer->translateGroupName('Admin')
```
php flarum info:
```
Flarum core 0.1.0-beta.10
PHP version: 7.2.19-0ubuntu0.18.04.2
Loaded extensions: Core, date, libxml, openssl, pcre, zlib, filter, hash, pcntl, Reflection, SPL, sodium, session, standard, mysqlnd, PDO, xml, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, json, exif, mysqli, pdo_mysql, Phar, posix, readline, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Zend OPcache
+------------------------------+----------------+--------+
| Flarum Extensions            |                |        |
+------------------------------+----------------+--------+
| ID                           | Version        | Commit |
+------------------------------+----------------+--------+
| flarum-approval              | v0.1.0-beta.8  |        |
| flarum-bbcode                | v0.1.0-beta.8  |        |
| flarum-emoji                 | v0.1.0-beta.10 |        |
| flarum-flags                 | v0.1.0-beta.9  |        |
| flarum-likes                 | v0.1.0-beta.9  |        |
| flarum-lock                  | v0.1.0-beta.9  |        |
| flarum-markdown              | v0.1.0-beta.10 |        |
| flarum-mentions              | v0.1.0-beta.10 |        |
| flarum-statistics            | v0.1.0-beta.9  |        |
| flarum-sticky                | v0.1.0-beta.9  |        |
| flarum-subscriptions         | v0.1.0-beta.9  |        |
| flarum-suspend               | v0.1.0-beta.9  |        |
| flagrow-sitemap              | 0.2.0          |        |
| fof-default-user-preferences | 0.2.0          |        |
| migratetoflarum-canonical    | 0.1.0          |        |
| flarumtr-turkish-lang        | v0.1.9         |        |
| flarum-tags                  | v0.1.0-beta.10 |        |
| fof-user-bio                 | 0.1.3          |        |
| fof-reactions                | 0.1.0          |        |
| tolgaaaltas-turkish          | 0.1.10.5       |        |
| v17development-seo           | 1.0.2          |        |
| fof-secure-https             | v0.1.0         |        |
| fof-ban-ips                  | dev-master     |        |
| flarum-embed                 | v0.1.0-beta.9  |        |
| fof-transliterator           | 0.1.1          |        |
| reflar-doorman               | 0.1.4          |        |
+------------------------------+----------------+--------+
Base URL: https://ekofibilim.flarum.cloud
Installation path: /data/host/ekofibilim/app
Debug mode: off
```

**Comment by Ralkage** [comment]
Hi @gwillem, this extension will be moved into the FoF space eventually, I would advise that this extension be disabled/uninstalled from FreeFlarum installations until then :)

We will also be removing all translation files except for English as this has been our ongoing approach since we decided to push translations to be added to language packs instead of pushing all translation maintainership on extension developers.

**Comment by gwillem** [comment]
Thanks!
