### ISSUE TITLE
start extension discover error

### ISSUE THREAD

**Issue by Wink541** [FriendsOfFlarum/doorman#59]
## Bug Report

**Current Behavior**
A clear and concise description of the behavior.

**Steps to Reproduce**
1. Go to 'admin#/extension/fof-doorman'
2. Click on 'button'
3. See error

**Expected Behavior**

**Screenshots**

**Environment**
- Flarum version: 1.3.0
- Extension version: 1.1.5
- Website URL: https://bbs.g0dsec.com/
- Webserver: nginx
- Hosting environment: vps
- PHP version: 8.2.0
- Browser: chrome 67

```
[INFO] Setting folder permissions
[INFO] Adding php extensions
fetch https://dl-cdn.alpinelinux.org/alpine/v3.16/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.16/community/x86_64/APKINDEX.tar.gz
(1/1) Installing php8-brotli (0.11.1-r1)
OK: 99 MiB in 84 packages
[INFO] Flarum already installed, init app...
Clearing the cache...
[INFO] Install extra bundled extensions
Using version ^1.3 for antoinefr/flarum-ext-money
Using version ^1.0 for antoinefr/flarum-ext-online
./composer.json has been updated
Running composer update antoinefr/flarum-ext-money antoinefr/flarum-ext-online flarum-lang/chinese-simplified fof/best-answer fof/profile-image-crop nearata/flarum-ext-copy-code-to-clipboard nearata/flarum-ext-tags-color-generator v17development/flarum-user-badges
Loading composer repositories with package information
Updating dependencies
Lock file operations: 8 installs, 0 updates, 0 removals
  - Locking antoinefr/flarum-ext-money (v1.3.1)
  - Locking antoinefr/flarum-ext-online (v1.0.1)
  - Locking flarum-lang/chinese-simplified (dev-master 5d3c03c)
  - Locking fof/best-answer (1.2.1)
  - Locking fof/profile-image-crop (1.1.5)
  - Locking nearata/flarum-ext-copy-code-to-clipboard (v2.1.0)
  - Locking nearata/flarum-ext-tags-color-generator (v2.2.0)
  - Locking v17development/flarum-user-badges (v1.0.0)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 8 installs, 0 updates, 0 removals
    0 [>---------------------------]    0 [->--------------------------]
  - Installing antoinefr/flarum-ext-money (v1.3.1): Extracting archive
  - Installing antoinefr/flarum-ext-online (v1.0.1): Extracting archive
  - Installing flarum-lang/chinese-simplified (dev-master 5d3c03c): Extracting archive
  - Installing fof/best-answer (1.2.1): Extracting archive
  - Installing fof/profile-image-crop (1.1.5): Extracting archive
  - Installing nearata/flarum-ext-copy-code-to-clipboard (v2.1.0): Extracting archive
  - Installing nearata/flarum-ext-tags-color-generator (v2.2.0): Extracting archive
  - Installing v17development/flarum-user-badges (v1.0.0): Extracting archive
 0/8 [>---------------------------]   0%
 5/8 [=================>----------]  62%
 8/8 [============================] 100%
1 package suggestions were added by new dependencies, use `composer suggest` to see details.
Package swiftmailer/swiftmailer is abandoned, you should avoid using it. Use symfony/mailer instead.
Generating autoload files
73 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
[INFO] Install extra bundled extensions: DONE
[INFO] Flarum already installed, init app: DONE
[INFO] End of startup script. Forum is starting.
```

**Possible solution(s)**

**Additional Context**
log is：
[2024-08-09 18:32:45] flarum.ERROR: Error: Call to undefined method Flarum\Extend\Model::cast() in /flarum/app/vendor/fof/doorman/extend.php:36
Stack trace:
#0 /flarum/app/vendor/flarum/core/src/Extension/Extension.php(376): require()
#1 /flarum/app/vendor/flarum/core/src/Extension/Extension.php(139): Flarum\Extension\Extension->getExtenders()
#2 /flarum/app/vendor/flarum/core/src/Extension/ExtensionManager.php(382): Flarum\Extension\Extension->extend()
#3 /flarum/app/vendor/flarum/core/src/Extension/ExtensionServiceProvider.php(31): Flarum\Extension\ExtensionManager->extend()
#4 [internal function]: Flarum\Extension\ExtensionServiceProvider->Flarum\Extension\{closure}()
#5 /flarum/app/vendor/flarum/core/src/Foundation/Application.php(329): call_user_func()
#6 /flarum/app/vendor/flarum/core/src/Foundation/Application.php(270): Flarum\Foundation\Application->fireAppCallbacks()
#7 /flarum/app/vendor/flarum/core/src/Foundation/InstalledSite.php(151): Flarum\Foundation\Application->boot()
#8 /flarum/app/vendor/flarum/core/src/Foundation/InstalledSite.php(82): Flarum\Foundation\InstalledSite->bootLaravel()
#9 /flarum/app/vendor/flarum/core/src/Http/Server.php(58): Flarum\Foundation\InstalledSite->bootApp()
#10 /flarum/app/vendor/flarum/core/src/Http/Server.php(35): Flarum\Http\Server->safelyBootAndGetHandler()
#11 /flarum/app/public/index.php(26): Flarum\Http\Server->listen()
#12 {main}

**Comment by DavideIadeluca** [comment]
You are using a very outdated version of `flarum/core`. Can you try installing the latest version and see if this resolves your issues? To be fair the version constraint should've been adjusted to prevent a install with a flarum version which doesn't have the `Model::cast()` method in the first place
